var content = {
	'highlight': {
		description: "",
		questions: "<p class='question'>Which tones were highlighted? <label for='toneA' id='toneAlabel'>A </label><select id='toneA'><option value='1'>1st</option><option value ='2'>2nd</option><option value='3'>3rd</option><option value='4'>4th</option><option value='5'>5th</option><option value='unsure'>Not sure</option></select><label for='toneB'>B </label><select id='toneB'><option value='1'>1st</option><option value='2'>2nd</option><option value='3'>3rd</option><option value='4'>4th</option><option value='5'>5th</option><option value='unsure'>Not sure</option></select></p><p class='question'>Which tone is shorter? <select id='shorterTone'><option>A</option><option>B</option><option value='unsure'>Not sure</option></select></p><p class='question'>What percent is the shorter of the longer? <input type='text' size='3' maxlength='3' id='percentAnswer' />% <i id='unsureInstructions'>Type '0' if you're unsure</i></p>"
	},
	'demographics': {
		description: "Thank you for working on this HIT. Please take a moment to fill out some demographic information about yourself.<b>Your answers have NOT been submitted yet -- please press submit below to finish.</b>", 
		questions: "<p class='question'>Which best describes your level of vision?<br /><input type='radio' name='visionAnswer' value='normal' />Normal or corrected to normal vision<br /><input type='radio' name='visionAnswer' value='low' />Low vision<br /><input type='radio' name='visionAnswer' value='blind' />Blind<br /><input type='radio' name='visionAnswer' value='na' />Prefer not to answer<br /></p><p class='question'>Have you ever had any musical training or musical practice?<br /><input type='radio' name='musicAnswer' value='yes' />Yes<br /><input type='radio' name='musicAnswer' value='no' />No<br /><input type='radio' name='musicAnswer' value='na' />Prefer not to answer<br /></p><p class='question'>What would you say is your musical skill level?<br /><input type='radio' name='musicSkillAnswer' value='1' />1 (Not very skilled)<br /><input type='radio' name='musicSkillAnswer' value='2' />2<br /><input type='radio' name='musicSkillAnswer' value='3' />3<br /><input type='radio' name='musicSkillAnswer' value='4' />4<br /><input type='radio' name='musicSkillAnswer' value='5' />5 (Very skilled)<br /><input type='radio' name='musicSkillAnswer' value='na' />Prefer not to answer<br /></p>"
	}
}